### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by YuanyeChi** [shuzhao-li-lab/asari#82]
```
Traceback (most recent call last):
  File "/usr/local/bin/asari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asari/main.py", line 191, in main
    process(parameters, args)
  File "/usr/local/lib/python3.11/site-packages/asari/main.py", line 55, in process
    __run_process__(parameters, args)
  File "/usr/local/lib/python3.11/site-packages/asari/main.py", line 51, in __run_process__
    process_project(list_input_files, parameters)
  File "/usr/local/lib/python3.11/site-packages/asari/workflow.py", line 85, in process_project
    EE.process_all()
  File "/usr/local/lib/python3.11/site-packages/asari/experiment.py", line 140, in process_all
    self.CMAP.build_composite_tracks()
  File "/usr/local/lib/python3.11/site-packages/asari/constructors.py", line 449, in build_composite_tracks
    self.calibrate_sample_RT(SM, list_mass_tracks, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asari/constructors.py", line 561, in calibrate_sample_RT
    sample.rt_cal_dict, sample.reverse_rt_cal_dict = calibration_fuction( 
                                                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asari/chromatograms.py", line 382, in rt_lowess_calibration
    ref_interpolated = [int(round(ii)) for ii in ref_interpolated]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asari/chromatograms.py", line 382, in <listcomp>
    ref_interpolated = [int(round(ii)) for ii in ref_interpolated]
                            ^^^^^^^^^
OverflowError: cannot convert float infinity to integer
```

Occurs when running asari on MTBLS136

**Comment by YuanyeChi** [comment]
fixed
