### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by YuanyeChi** [shuzhao-li-lab/asari#85]
```
Traceback (most recent call last):
  File "/usr/local/bin/asari", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/asari/main.py", line 182, in main
    process(parameters, args)
  File "/usr/local/lib/python3.10/site-packages/asari/main.py", line 48, in process
    __run_process__(parameters, args)
  File "/usr/local/lib/python3.10/site-packages/asari/main.py", line 45, in __run_process__
    process_project(list_input_files, parameters )
  File "/usr/local/lib/python3.10/site-packages/asari/workflow.py", line 84, in process_project
    EE = ext_Experiment(sample_registry, parameters)
  File "/usr/local/lib/python3.10/site-packages/asari/experiment.py", line 58, in __init__
    self.number_scans = self.get_max_scan_number(sample_registry)
  File "/usr/local/lib/python3.10/site-packages/asari/experiment.py", line 113, in get_max_scan_number
    return max([sample_registry[k]['max_scan_number'] for k in self.valid_sample_ids]) + 1
ValueError: max() arg is an empty sequence
```

with command

`singularity exec --bind /projects/sh-li-lab/:/data /projects/sh-li-lab/share/YC/asari_amd_1.12.4.sif asari process --autoheight True --ppm 10 --mode pos --cores 24 -i "$subdir" -o "$output_path/asari" -j "ST000725_HILICpos_${subdir_name}_ppm5" | tee "$output_path/ST000725_HILICpos_${subdir_name}_ppm5.txt"`

on some tof datasets

**Comment by shuzhao-li** [comment]
Looks like no valid sample.

**Comment by YuanyeChi** [comment]
Cool! I am retrieving and reproducing these error. If so, then I can just skip these datasets.

**Comment by YuanyeChi** [comment]
~~~~~~~ Hello from Asari (1.12.4) ~~~~~~~~~

Working on ~~ /projects/sh-li-lab/public_data_mzml/metabolomics_workbench/ST000987/study/RPpos ~~ 


Estimating parameter for min peak_height based on  ['/projects/sh-li-lab/public_data_mzml/metabolomics_workbench/ST000987/study/RPpos/GLA_CT_Lipids_QC03.mzML', '/projects/sh-li-lab/public_data_mzml/metabolomics_workbench/ST000987/study/RPpos/GLA_CT_Lipids_SO061_SA074_1003cC1.mzML', '/projects/sh-li-lab/public_data_mzml/metabolomics_workbench/ST000987/study/RPpos/GLA_CT_Lipids_SO111_SA102_1007aC3.mzML']
Error in analyzing  /projects/sh-li-lab/public_data_mzml/metabolomics_workbench/ST000987/study/RPpos/GLA_CT_Lipids_QC03.mzML
Error in analyzing  /projects/sh-li-lab/public_data_mzml/metabolomics_workbench/ST000987/study/RPpos/GLA_CT_Lipids_SO061_SA074_1003cC1.mzML
Error in analyzing  /projects/sh-li-lab/public_data_mzml/metabolomics_workbench/ST000987/study/RPpos/GLA_CT_Lipids_SO111_SA102_1007aC3.mzML
Problems with input files: cannot convert float NaN to integer. Back to default min_peak_height.

**Comment by shuzhao-li** [comment]
We have not seen NaN in our data or other Orbi I think.
Let's add a step to convert NaN to 0 for TOF.

**Comment by YuanyeChi** [comment]
Will do later today

**Comment by YuanyeChi** [comment]
The reason is pymzml cannot read mzML files from ST000987

**Comment by YuanyeChi** [comment]
[011QC_3rd 200.mzML.zip](https://github.com/user-attachments/files/20396438/011QC_3rd.200.mzML.zip)

Web app user J. Bozelli reported this issue again with his ToF data. I noticed pymzml is not able to read spectra's intensities in his given mzML. 

Here is the code snippet from asari. 

```
import pymzml

infile = 'input_bozelli/011QC_3rd 200.mzML'
rt_times = [] 
min_intensity=100
ms2_spectra = []
ms_expt = exp = pymzml.run.Reader(infile)
for spec in ms_expt:
        if spec.ms_level == 1:                         # MS Level 1 only
            rt_times.append(spec.scan_time_in_minutes()*60)
            intensities = spec.i.astype(int)
            good_positions = intensities > min_intensity
            alldata += [(mz, ii, inten) for mz, inten in zip(spec.mz[good_positions], intensities[good_positions])]
            ii += 1
```

Error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 11
      9 if spec.ms_level == 1:                         # MS Level 1 only
     10     rt_times.append(spec.scan_time_in_minutes()*60)
---> 11     intensities = spec.i.astype(int)
     12     good_positions = intensities > min_intensity
     13     alldata += [(mz, ii, inten) for mz, inten in zip(spec.mz[good_positions], intensities[good_positions])]

File ~/Projects/computational/asari/venv/lib/python3.12/site-packages/pymzml/spec.py:1071, in Spectrum.i(self)
   1069 if self._i is None:
   1070     params = self._get_encoding_parameters("intensity array")
-> 1071     self._i = self._decode(*params)
   1072 return self._i

File ~/Projects/computational/asari/venv/lib/python3.12/site-packages/pymzml/spec.py:303, in MS_Spectrum._decode_to_numpy(self, data, d_array_length, data_type, comp)
    300         out_data = np.frombuffer(out_data, i_type)
    301     # TODO elif data_type == "null-terminated ASCII string":
    302     else:
--> 303         raise ValueError(f"Unsupported data type: {data_type}")
    304 else:
    305     out_data = np.array([])

ValueError: Unsupported data type: None

```

Then I scan through all spectra of this mzML, all spectra's intensities are None. I am not sure what's cause of the Nones. Is it possible to be caused by inappropriate parameters set during his raw file conversion? Seems not asari's problem, but just reopen this to double check. 

Also attached the problem mzML file for your reference.

**Comment by shuzhao-li** [comment]
Likely bad mzML conversion. We already catch errors on bad input files.  We can add this one (bad input values) later.

**Comment by YuanyeChi** [comment]
```
from pyopenms import MSExperiment, MzMLFile

exp = MSExperiment()
MzMLFile().load("input_bozelli/011QC_3rd 200.mzML", exp)

for i, spec in enumerate(exp.getSpectra()):
    mz_array, intensity_array = spec.get_peaks()

    print(mz_array, intensity_array)
```

I just tried pyopenms since it is available on arm64 mac, and found it can read mzs and intensities from this input. Maybe pymzml does not support some vendor's converted format.

**Comment by jmmitc06** [comment]
I believe I will have the origin .raw file or .d from him soon. He has an agilent instrument and used MSConvert. It should have worked. I wonder if pymzml assumes a scan cannot be empty but depending on instrument configuration that may be possible.
